### ISSUE TITLE
Visualization for factor graph optimization

### ISSUE THREAD

**Issue by weisongwen** [aorthey/orthoklampt#6]
Hi @aorthey , Thanks for your great work,

I am curious about if this package can be applied to visualize the factor graph optimization for robot SLAM.

Best,
Welson,

**Comment by aorthey** [comment]
Hi @weisongwen. I somehow did not track the Issues with the repo, sorry for the late answer.... I am actually not an expert on SLAM or factor graphs, so I don't know. If you are still interested in that, please just drop me an email with some more context and I could have a look.

**Comment by weisongwen** [comment]
Hi @aorthey  Thanks for your kind reply. I will look into your work first and let you know if I have any questions further. 

Thanks again for your reply :-)

Best,
Weisong,
