### ISSUE TITLE
fetal error:ompl/multilevel/planners/explorer/MotionExplorer.h: No such file or directory

### ISSUE THREAD

**Issue by Robotics-Zhikai** [aorthey/orthoklampt#7]
Hi,   @aorthey ,Thanks for your great work!
There comes a problem when I run "install_script.sh".
Specificly,when I run "make -j$(nproc) planner_gui" in last Step:"Installing MotionPlanningExplorerGUI",
a "MotionExplorer/src/planner/planner.cpp:13:62:  fetal error:ompl/multilevel/planners/explorer/MotionExplorer.h: No such file or directory  #include <ompl/multilevel/planners/explorer/MotionExplorer.h>"came out.
The position of the error is behind the  “[26%]Building CXX object CMakeFiles/planner_gui.dir/src/planner/planner.cpp.o.”
I have spent a day to solve this problem, but still no success.
Looking forward to your help!Thank you very much！

**Comment by aorthey** [comment]
Hi @Robotics-Zhikai , sorry that you couldn't install it right away. The error comes from some new files we did not yet push to the master branch. I just had a look and updated the master branch to be consistent with OMPL. Could you try again with the new version? Let me know if you have any more problems.

**Comment by Robotics-Zhikai** [comment]
Hi, @aorthey ,Thank you for your help！

**Comment by aorthey** [comment]
No problem. Be advised that the multilevel parts are quite robust and stable, but the Local-Minima visualizer is still under active development and might need some additional tuning to get working on a particular use case. Do not hesitate to reach out by mail if you have issues or want to discuss something.
