### ISSUE TITLE
installation for ubuntu 22.04

### ISSUE THREAD

**Issue by saraybakker1** [aorthey/orthoklampt#8]
Hi Andreas Orthey,

I was checking out your paper and code on fiber bundles and visualizing local minima and found it very interesting.
I was wondering if there are installation instructions available for Ubuntu 22.04?

**Comment by aorthey** [comment]
Dear Saray,

Thank you for your interest. Unfortunately, we are not actively maintaining the library, and there are multiple dependencies which need to be updated to work under 22.04. However, most of the code about fiber bundles has been merged into OMPL, and you can basically use it without requiring this package. You can find a tutorial here: https://ompl.kavrakilab.org/multiLevelPlanningTutorial.html. Let me know if you have any more questions!

Hope this helps,
Best,
Andreas

**Comment by saraybakker1** [comment]
Hi Andreas,

Thank you for your help. I will check the tutorial on the ompl website.

With kind regards,

Saray
